const ActionsEnum = {
    ADD_INGREDIENT: "ADD_INGREDIENT",
    REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
    SET_INGREDIENTS: "SET_INGREDIENTS",
    SET_ERROR: "SET_ERROR"
};

export default ActionsEnum;
